export const products = [
    {
      key: 'p1',
      name: 'Durable Backpack',
      price: 75,
      group: 'Backpacks',
      inStock: true,
    },
    {
      key: 'p2',
      name: 'Waterproof Jacket',
      price: 150,
      group: 'Jackets',
      inStock: true,
    },
    {
      key: 'p3',
      name: 'Fitness Tracker',
      price: 100,
      group: 'Electronics',
      inStock: true,
    },
    {
      key: 'p4',
      name: 'Smartphone',
      price: 500,
      group: 'Electronics',
      inStock: true,
    },
    {
      key: 'p5',
      name: 'Running Shoes',
      price: 90,
      group: 'Footwear',
      inStock: false,
    },
    {
      key: 'p6',
      name: 'Stainless Steel Water Bottle',
      price: 25,
      group: 'Water Bottles',
      inStock: true,
    },
    {
      key: 'p7',
      name: 'Comfortable Headphones',
      price: 80,
      group: 'Electronics',
      inStock: true,
    },
    {
      key: 'p8',
      name: 'Cotton T-Shirt',
      price: 20,
      group: 'Clothing',
      inStock: true,
    },
    {
      key: 'p9',
      name: 'Hiking Boots',
      price: 200,
      group: 'Footwear',
      inStock: true,
    },
    {
      key: 'p10',
      name: 'Leather Wallet',
      price: 50,
      group: 'Accessories',
      inStock: false,
    },
    {
      key: 'p11',
      name: 'Sleeping Bag',
      price: 175,
      group: 'Camping Gear',
      inStock: true,
    },
    {
      key: 'p12',
      name: 'Sneakers',
      price: 80,
      group: 'Footwear',
      inStock: true,
    },
    {
      key: 'p13',
      name: 'LED Desk Lamp',
      price: 60,
      group: 'Electronics',
      inStock: true,
    },
    {
      key: 'p14',
      name: 'Baseball Cap',
      price: 15,
      group: 'Hats',
      inStock: true,
    },
    {
      key: 'p15',
      name: 'Cycling Gloves',
      price: 40,
      group: 'Accessories',
      inStock: false,
    },
    {
      key: 'p16',
      name: 'Stainless Steel Cutlery Set',
      price: 35,
      group: 'Kitchenware',
      inStock: true,
    },
    {
      key: 'p17',
      name: 'Travel Mug',
      price: 30,
      group: 'Water Bottles',
      inStock: true,
    },
    {
      key: 'p18',
      name: 'Hair Dryer',
      price: 60,
      group: 'Beauty',
      inStock: true,
    },
    {
      key: 'p19',
      name: 'Television',
      price: 800,
      group: 'Electronics',
      inStock: false,
    },
    {
      key: 'p20',
      name: 'Winter Coat',
      price: 300,
      group: 'Clothing',
      inStock: true,
    },
    {
      key: 'p21',
      name: 'Winter Backpack',
      price: 150,
      group: 'Backpacks',
      inStock: true,
    },
    {
      key: 'p22',
      name: 'Summer Backpack',
      price: 100,
      group: 'Backpacks',
      inStock: true,
    },
  ];  